"""AEDT-driven workflow contracts and manual handoff/runtime utilities.

Ownership: SCGSim Development.
Failure intent: public entrypoints preserve explicit partial adaptive-history
records, but reject corrupt or identity-inconsistent state without fallback.
"""

from ._epr_geometry import planar_junction_from_port, prepare_planar_geometry_input
from ._epr_models import (
    EprAnalysisRequest,
    EprResult,
    ExpressionCacheConvergence,
    NativeExpressionDefinition,
    NormalizedSurfaceEprTotal,
    PlanarJunction,
    PreparedPlanarGeometry,
    SavedSolution,
    SurfaceEprSpec,
)
from ._epr_results import (
    combine_epr_mode,
    combine_surface_epr_mode,
    plot_epr_result,
    reanalyze_epr,
    resolve_epr_result,
    resolve_saved_solution,
    show_epr,
)
from .eigenmode import EigenmodeSim
from .handoff import (
    HandoffPlan,
    analyze_epr,
    prepare_handoff,
    prepare_hfss_eigenmode_from_geometry,
    prepare_q3d_from_geometry,
)
from .resolve import ResolvedRun, resolve_results
from .spec import (
    AedtResources,
    AedtSpec,
    EigenmodeRunControl,
    FrequencySweepSpec,
    HfssDrivenMode,
    HfssDrivenSpec,
    HfssEigenmodeSpec,
    HfssEprAnalysisSpec,
    HfssEprSpec,
    HfssRunControl,
    HfssSpec,
    LayerImport,
    LengthMeshSpec,
    MatrixRunControl,
    ModalPort,
    ObjectBinding,
    PdkMaterial,
    Q2dConductorSpec,
    Q2dRectangleSpec,
    Q2dSpec,
    Q3dBodySpec,
    Q3dNetSpec,
    Q3dSpec,
    TerminalPort,
    parse_aedt_spec,
)

__all__ = [
    "AedtResources",
    "AedtSpec",
    "EigenmodeRunControl",
    "EigenmodeSim",
    "EprAnalysisRequest",
    "EprResult",
    "ExpressionCacheConvergence",
    "FrequencySweepSpec",
    "HandoffPlan",
    "HfssDrivenMode",
    "HfssDrivenSpec",
    "HfssEigenmodeSpec",
    "HfssEprAnalysisSpec",
    "HfssEprSpec",
    "HfssRunControl",
    "HfssSpec",
    "LayerImport",
    "LengthMeshSpec",
    "MatrixRunControl",
    "ModalPort",
    "NativeExpressionDefinition",
    "NormalizedSurfaceEprTotal",
    "ObjectBinding",
    "PdkMaterial",
    "PlanarJunction",
    "PreparedPlanarGeometry",
    "Q2dConductorSpec",
    "Q2dRectangleSpec",
    "Q2dSpec",
    "Q3dBodySpec",
    "Q3dNetSpec",
    "Q3dSpec",
    "ResolvedRun",
    "SavedSolution",
    "SurfaceEprSpec",
    "TerminalPort",
    "analyze_epr",
    "combine_epr_mode",
    "combine_surface_epr_mode",
    "parse_aedt_spec",
    "planar_junction_from_port",
    "plot_epr_result",
    "prepare_handoff",
    "prepare_hfss_eigenmode_from_geometry",
    "prepare_planar_geometry_input",
    "prepare_q3d_from_geometry",
    "reanalyze_epr",
    "resolve_epr_result",
    "resolve_results",
    "resolve_saved_solution",
    "show_epr",
]
