[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "scgsim"
version = "1.0.0.dev1"
description = "Research-first electromagnetic simulation workflows for superconducting circuits."
readme = "README.md"
requires-python = "~=3.12.0"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]

[project.optional-dependencies]
aedt = [
    "gdstk",
    "pyaedt==1.3.0",
]
palace = [
    "gdsfactory>=9,<10",
    "gdstk",
    "gmsh",
    "plotly>=6.0.0",
]
dev = [
    "jupytext",
    "nbformat",
]

[project.urls]
Homepage = "https://github.com/OrPenStrike/scgsim"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
