[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "scgsim"
version = "0.1.0.dev0"
description = "Research-first electromagnetic simulation workflows for superconducting circuits."
requires-python = "~=3.12.0"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]

[project.urls]
Homepage = "https://github.com/OrPenStrike/scgsim"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
